name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies globally
      run: |
        uv pip install -r .devcontainer/requirements.txt
      env:
        UV_SYSTEM_PYTHON: 1

    - name: Run tests
      run: |
        pytest
