name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Specify your desired Python version

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Install dependencies globally
      run: uv pip install -r .devcontainer/requirements.txt

    - name: Run tests
      run: pytest
