name: PR Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Set up Python and create virtual environment
      run: |
        uv python install
        echo "VIRTUAL_ENV=$(pwd)/.venv" >> $GITHUB_ENV
        echo "PATH=$(pwd)/.venv/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: uv pip install -r .devcontainer/requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
